ext {
    ftcVersion = '10.1.1'
}

if (project.name == 'FtcRobotController') {
    dependencies {
        implementation "org.firstinspires.ftc:Inspection:${ftcVersion}"
        implementation "org.firstinspires.ftc:Blocks:${ftcVersion}"
        implementation "org.firstinspires.ftc:RobotCore:${ftcVersion}"
        implementation "org.firstinspires.ftc:RobotServer:${ftcVersion}"
        implementation "org.firstinspires.ftc:OnBotJava:${ftcVersion}"
        implementation "org.firstinspires.ftc:Hardware:${ftcVersion}"
        implementation "org.firstinspires.ftc:FtcCommon:${ftcVersion}"
        implementation "org.firstinspires.ftc:Vision:${ftcVersion}"

        implementation 'androidx.appcompat:appcompat:1.7.1'

        implementation fileTree(dir: 'libs', include: ['*.jar'])
    }
}
